version: "3"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=dabbleme_development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_POOL=4
    links:
      - db
  db:
    image: postgres:12.1
volumes:
  bundle_cache:
